### ISSUE TITLE
Ip adress not working ? 

### ISSUE THREAD

**Issue by lastpeony** [spencer-hanson/BasicJavaRAT#1]
Hi its working on localhost but between 2 computers it cant connect looks like there is a problem with  224.134.68.1 adresss how to fix it actually i couldnt really understand that part where is this application connecting ? 

thanks

**Comment by spencer-hanson** [comment]
Hello, thanks for taking interest in my project.
It looks to me like you're trying to access a computer across the internet, using an external ip address verses an internal ip address. Take a look at this guide for information on how those work: http://www.steves-internet-guide.com/internal-external-ip-addresses/

I'm not sure if it has the capability to work across the internet, but if you could set up port-forwarding on 6050 that could work.

**Comment by lastpeony** [comment]
hi thanks for answering.
do you have any idea to make it work across the internet on any computer ?

**Comment by spencer-hanson** [comment]
Yes, as I said above, try port fowarding the address.
http://www.steves-internet-guide.com/internal-external-ip-addresses/
